changelog:
  categories:
    - title: ":sparkles: New features"
      labels:
        - ":sparkles:: enhancement"
    - title: ":bug: Fixed bugs"
      labels:
        - ":bug:: bug"
    - title: Other Changes
      labels:
        - "*"
