extends:
  - "stylelint-plugin-stylus/standard"
  - stylelint-config-recess-order
plugins:
  - stylelint-stylistic
  - stylelint-declaration-block-no-ignored-properties
rules:
  number-leading-zero: null
  stylus/number-leading-zero: never
  block-no-empty: null
  selector-class-pattern: null
  stylistic/block-closing-brace-empty-line-before: never
  declaration-empty-line-before: null
  stylistic/indentation: 2
  stylistic/no-eol-whitespace: true
  stylistic/no-extra-semicolons: true
  stylistic/no-missing-end-of-source-newline: true
  plugin/declaration-block-no-ignored-properties: true
  color-function-notation: null
  hue-degree-notation: null
  order/properties-alphabetical-order: null
  order/properties-order:
    - 
      groupName: all
      emptyLineBefore: never
      noEmptyLineBetween: true
      properties:
        - all
    - 
      groupName: self-position
      emptyLineBefore: never
      noEmptyLineBetween: true
      properties:
        - content
        - visibility
        - z-index
        - pointer-events
        - cursor
        - grid-area
        - position
        - inset
        - top
        - left
        - right
        - bottom
        - width
        - max-width
        - min-width
        - height
        - max-height
        - min-height
        - aspect-ratio
    - 
      groupName: self-design
      emptyLineBefore: always
      noEmptyLineBetween: true
      properties:
        - list-style
        - margin
        - margin-top
        - margin-left
        - margin-right
        - margin-bottom
        - padding
        - padding-top
        - padding-left
        - padding-right
        - padding-bottom
        - box-sizing
        - background
        - background-color
        - color
        - border-radius
        - border-top-left-radius
        - border-top-right-radius
        - border-bottom-left-radius
        - border-bottom-right-radius
        - border
        - border-width
        - border-style
        - border-color
        - outline
        - outline-color
        - outline-style
        - outline-width
        - outline-offset
    - 
      groupName: child-position
      emptyLineBefore: always
      noEmptyLineBetween: true
      properties:
        - overflow
        - overflow-x
        - overflow-y
        - display
        - text-align
