name: deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            pnpm build

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: deploy_key
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          config: |
            Host deploy
              HostName ${{ secrets.SSH_HOSTNAME }}
              User ${{ secrets.SSH_USERNAME }}
              IdentityFile ~/.ssh/deploy_key

      - name: Run deploy script
        run: rsync -acvz dist/ deploy:${{ secrets.DEPLOY_TARGET }}
